### ISSUE TITLE
why cblas library is included in repo ?

### ISSUE THREAD

**Issue by avilleret** [CICM/HoaLibrary#22]
hello, 

I'm wondering why there are headers and binary of Cblas library in the repo.
Are they different from the ones we can get from package manager like apt-get in Ubuntu ?
If so, what is the difference ? and what about ARM arch and others ?

**Comment by pierreguillot** [comment]
The repository has already binary files and stuff like that so why not include cblas ? ...  I know it's a mess that why we have done a brand new repository : https://github.com/CICM/HoaLibrary-Light.
Cheers
