### ISSUE TITLE
hoa.decoder object auto routing signals

### ISSUE THREAD

**Issue by eflynch** [CICM/HoaLibrary#24]
When I route cables from [hoa.decoder~ ] in Max to another object, and then save the patch, close and reopen it, new cables are automatically routed from the first outlet to every object that the other outlets are routed to. I'm not sure if this is an HOA bug or a Max bug.

This is happening in Max 7.0.0 with HoaLibrary 2.0.1
Example
[hoa.decoder~ 3] : __. [sig~]

Save/Close/Reopen

[hoa.decoder~ 3] :>----___. [sig~]

**Comment by eliottparis** [comment]
Hi,
Try to add "@autoconnect 0" (default to 1) to the hoa.2d.decoder~ and tell us if it's better.

**Comment by eflynch** [comment]
With @autoconnect 0 does fix the problem.

**Comment by ssfrr** [comment]
Is this the expected default behavior? Seems sort of confusing to me.

**Comment by eliottparis** [comment]
Hi, it's obviously not the correct behavior. @Autoconnect try to do its best to facilitate patching when configuration change (reconnects patchlines to the hoa.gain~/hoa.2d.meter~/hoa.dac~ when number of channels changed, synchronizes angles and offset between decoder and meter...); But we can't provide all user expectations. If it does not fit your needs, deactivate it !
However, we ca

**Comment by eflynch** [comment]
If I do this:
![screen shot 2015-03-18 at 10 02 38 am](https://cloud.githubusercontent.com/assets/1323509/6710300/0ce9c24c-cd56-11e4-8902-3aee3a2ee215.png)
I expect it to remain that way. However, if I reopen the patch, it autoconnects to this:


![screen shot 2015-03-18 at 10 03 00 am](https://cloud.githubusercontent.com/assets/1323509/6710299/0ce66b74-cd56-11e4-969e-dc6fa1992fdd.png)
which is not what I expect.

**Comment by eliottparis** [comment]
I can can confirm that, we will try to fix this up before the next release.
Thanks.

**Comment by eliottparis** [comment]
Hi, this has been fixed in the new release ([v2.2](https://github.com/CICM/HoaLibrary-Max/releases)).
