### ISSUE TITLE
Pd-0.48-1 Installation

### ISSUE THREAD

**Issue by balandinodidonato** [CICM/HoaLibrary#26]
### System info
- Computer: MacBook Pro 15" late 2015
- OS: maOS High Sierra 10.13.4
- Pure Data version: 0.48-1

### To reproduce
- Install [Pd-0.48.1](http://puredata.info/downloads/pure-data/releases/0.48-1)
- Download [HoaLibrary for Pure Data v2.1](https://github.com/CICM/HoaLibrary/releases/tag/v2.1.(pd))
- Install by copying the folder in `/Applications/Pd-0.48-1.app/Contents/Resources/extra` folder or in `Documents/Pd/externals` (Pd default external folder)
- Open any help file of the library

### Expected
- Any help file would open with no errors

### Actual
- The help file opens yet the hoa objects are not found

**Comment by grammaton** [comment]
Hi Balandino,
Same problem to me. 
There is a thread here

https://www.mail-archive.com/pd-list@lists.iem.at/msg13958.html

**Comment by balandinodidonato** [comment]
Hi @grammaton I was meant to ask you about that. I knew you were on it too! please let me know as soon as you know of any solution to this problem!

**Comment by jayrope** [comment]
Same here, on 10.9.5 - pd 48-1. As there isn't sooo much variety on ambisonics for pd a soon fix would be very appreciated.

**Comment by jayrope** [comment]
Uhm, it looks like we are not getting a fix, or are we?

**Comment by pierreguillot** [comment]
This repository is no more maintained since 2015.
